spring:
  datasource:
    url: jdbc:mysql://module-4-db.cv4qgjtvjoyq.eu-central-1.rds.amazonaws.com:3306/module_4_db
    username: admin
    password: rootadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
security:
  jwt:
    secret-key: bETTERl@TEtHE@NnEVER~